/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { TxVerifier, TxVerifierInterface } from "../TxVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IBtcMirror",
        name: "in_mirror",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "getBtcRelay",
    outputs: [
      {
        internalType: "contract IBtcMirror",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "minConfirmations",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "blockNum",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "bytes",
            name: "blockHeader",
            type: "bytes",
          },
          {
            internalType: "bytes32",
            name: "txId",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "txIndex",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "txMerkleProof",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "rawTx",
            type: "bytes",
          },
        ],
        internalType: "struct BtcTxProof",
        name: "inclusionProof",
        type: "tuple",
      },
      {
        internalType: "uint256",
        name: "txOutIx",
        type: "uint256",
      },
    ],
    name: "verifiedP2PKHPayment",
    outputs: [
      {
        internalType: "bytes20",
        name: "out_actualPubkeyhash",
        type: "bytes20",
      },
      {
        internalType: "uint64",
        name: "out_sats",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "minConfirmations",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "blockNum",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "bytes",
            name: "blockHeader",
            type: "bytes",
          },
          {
            internalType: "bytes32",
            name: "txId",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "txIndex",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "txMerkleProof",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "rawTx",
            type: "bytes",
          },
        ],
        internalType: "struct BtcTxProof",
        name: "inclusionProof",
        type: "tuple",
      },
      {
        internalType: "uint256",
        name: "txOutIx",
        type: "uint256",
      },
    ],
    name: "verifiedP2SHPayment",
    outputs: [
      {
        internalType: "bytes20",
        name: "out_actualScripthash",
        type: "bytes20",
      },
      {
        internalType: "uint64",
        name: "out_sats",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class TxVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): TxVerifierInterface {
    return new Interface(_abi) as TxVerifierInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): TxVerifier {
    return new Contract(address, _abi, runner) as unknown as TxVerifier;
  }
}
