/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type BtcTxProofStruct = {
  blockHeader: BytesLike;
  txId: BytesLike;
  txIndex: BigNumberish;
  txMerkleProof: BytesLike;
  rawTx: BytesLike;
};

export type BtcTxProofStructOutput = [
  blockHeader: string,
  txId: string,
  txIndex: bigint,
  txMerkleProof: string,
  rawTx: string
] & {
  blockHeader: string;
  txId: string;
  txIndex: bigint;
  txMerkleProof: string;
  rawTx: string;
};

export interface TxVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getBtcRelay"
      | "supportsInterface"
      | "verifiedP2PKHPayment"
      | "verifiedP2SHPayment"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getBtcRelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedP2PKHPayment",
    values: [BigNumberish, BigNumberish, BtcTxProofStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedP2SHPayment",
    values: [BigNumberish, BigNumberish, BtcTxProofStruct, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getBtcRelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedP2PKHPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedP2SHPayment",
    data: BytesLike
  ): Result;
}

export interface TxVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): TxVerifier;
  waitForDeployment(): Promise<this>;

  interface: TxVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getBtcRelay: TypedContractMethod<[], [string], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  verifiedP2PKHPayment: TypedContractMethod<
    [
      minConfirmations: BigNumberish,
      blockNum: BigNumberish,
      inclusionProof: BtcTxProofStruct,
      txOutIx: BigNumberish
    ],
    [[string, bigint] & { out_actualPubkeyhash: string; out_sats: bigint }],
    "view"
  >;

  verifiedP2SHPayment: TypedContractMethod<
    [
      minConfirmations: BigNumberish,
      blockNum: BigNumberish,
      inclusionProof: BtcTxProofStruct,
      txOutIx: BigNumberish
    ],
    [[string, bigint] & { out_actualScripthash: string; out_sats: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getBtcRelay"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifiedP2PKHPayment"
  ): TypedContractMethod<
    [
      minConfirmations: BigNumberish,
      blockNum: BigNumberish,
      inclusionProof: BtcTxProofStruct,
      txOutIx: BigNumberish
    ],
    [[string, bigint] & { out_actualPubkeyhash: string; out_sats: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifiedP2SHPayment"
  ): TypedContractMethod<
    [
      minConfirmations: BigNumberish,
      blockNum: BigNumberish,
      inclusionProof: BtcTxProofStruct,
      txOutIx: BigNumberish
    ],
    [[string, bigint] & { out_actualScripthash: string; out_sats: bigint }],
    "view"
  >;

  filters: {};
}
